package viewer

import (
	"os"
	"testing"
)

func TestParse_RealLogFile(t *testing.T) {
	// This test uses a real log file generated by drillog
	// Run: go run ./examples/device-sync/ 2> testdata/device-sync.log
	f, err := os.Open("testdata/device-sync.log")
	if os.IsNotExist(err) {
		t.Skip("testdata/device-sync.log not found, skipping integration test")
	}
	if err != nil {
		t.Fatalf("failed to open test file: %v", err)
	}
	defer f.Close()

	result, err := Parse(f)
	if err != nil {
		t.Fatalf("Parse failed: %v", err)
	}

	if result.Format != FormatText {
		t.Errorf("expected FormatText, got %v", result.Format)
	}

	// Should have entries
	if len(result.Entries) == 0 {
		t.Error("expected entries, got none")
	}

	// All entries should have span IDs
	for i, e := range result.Entries {
		if e.Span == "" {
			t.Errorf("entry %d: missing span ID", i)
		}
	}

	// Count root spans (no parent) and child spans
	roots := 0
	children := 0
	for _, e := range result.Entries {
		if e.Parent == "" {
			roots++
		} else {
			children++
		}
	}

	t.Logf("Parsed %d entries: %d root, %d children", len(result.Entries), roots, children)

	if roots == 0 {
		t.Error("expected at least one root entry (no parent)")
	}
	if children == 0 {
		t.Error("expected at least one child entry (with parent)")
	}
}
