// Command drillog is a CLI tool for viewing hierarchical logs.
//
// Usage:
//
//	drillog view <logfile>
//
// This parses a log file generated by the drillog library and serves
// an interactive web UI to explore the log hierarchy.
package main

import (
	"flag"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/exec"
	"runtime"

	"github.com/deviantony/drillog/internal/viewer"
)

const usage = `drillog - hierarchical log viewer

Usage:
  drillog view <logfile>    View a log file in the browser

Examples:
  drillog view app.log
  drillog view /var/log/myapp/debug.log

The viewer parses logs generated by the drillog library and displays
them as an interactive tree in your browser.
`

func main() {
	if len(os.Args) < 2 {
		fmt.Print(usage)
		os.Exit(1)
	}

	switch os.Args[1] {
	case "view":
		if err := runView(os.Args[2:]); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
	case "-h", "--help", "help":
		fmt.Print(usage)
	default:
		fmt.Fprintf(os.Stderr, "Unknown command: %s\n\n", os.Args[1])
		fmt.Print(usage)
		os.Exit(1)
	}
}

func runView(args []string) error {
	fs := flag.NewFlagSet("view", flag.ExitOnError)
	port := fs.Int("port", 0, "port to serve on (default: auto-select)")
	host := fs.String("host", "localhost", "host to bind to (use 0.0.0.0 for all interfaces)")
	noBrowser := fs.Bool("no-browser", false, "don't open browser automatically")

	if err := fs.Parse(args); err != nil {
		return err
	}

	if fs.NArg() < 1 {
		return fmt.Errorf("missing log file argument\n\nUsage: drillog view <logfile>")
	}

	logFile := fs.Arg(0)

	// Open and parse log file
	f, err := os.Open(logFile)
	if err != nil {
		return fmt.Errorf("opening log file: %w", err)
	}
	defer f.Close()

	fmt.Printf("Parsing %s...\n", logFile)

	result, err := viewer.Parse(f)
	if err != nil {
		return fmt.Errorf("parsing log file: %w", err)
	}

	if len(result.Entries) == 0 {
		return fmt.Errorf("no valid log entries found in %s", logFile)
	}

	// Build tree
	tree := viewer.BuildTree(result.Entries)
	stats := tree.Stats()

	fmt.Printf("Loaded %d log entries, %d spans\n", stats.TotalLogs, stats.TotalSpans)

	// Create server
	server := viewer.NewServer(tree, result.Entries)

	// Find available port
	addr := fmt.Sprintf("%s:%d", *host, *port)
	listener, err := net.Listen("tcp", addr)
	if err != nil {
		return fmt.Errorf("starting server: %w", err)
	}

	actualAddr := listener.Addr().String()
	url := fmt.Sprintf("http://%s", actualAddr)

	fmt.Printf("Serving on %s\n", url)

	// Open browser
	if !*noBrowser {
		go openBrowser(url)
	}

	// Start server (blocks)
	return http.Serve(listener, server)
}

// openBrowser opens the default browser to the given URL.
func openBrowser(url string) {
	var cmd *exec.Cmd

	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", url)
	case "linux":
		cmd = exec.Command("xdg-open", url)
	case "windows":
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", url)
	default:
		fmt.Printf("Open %s in your browser\n", url)
		return
	}

	// Ignore errors - browser opening is best-effort
	_ = cmd.Start()
}
